spring:
  application:
    name: agenda-service
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/bd_agenda?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 9101

api:
  base-url: http://api-gateway:9090
  cliente:
    exists: /clientes/%d/exists
  sucursal:
    exists: /sucursales/%d/exists
  

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  file:
    name: logs/agenda-service.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"
