# Perfil de produccion (Railway / Render)
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    com.example: INFO
    root: WARN
