spring:
  application:
    name: pagos-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/bd_pagos?createDatabaseIfNotExist=true
    username: root
    password: ""
  liquibase:
    change-log: classpath:db/changelog/db.changelog-001-pago.sql
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 9095

api:
  base-url: http://api-gateway:9090
  compra:
    exists: /compras/%d/exists

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  file:
    name: logs/pagos-service.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"
