spring:
  application:
    name: reservas-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/bd_reservas?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 9096

api:
  base-url: http://api-gateway:9090
  usuario:
    exists: /usuarios/%d/exists
  servicio:
    exists: /servicios/%d/exists
    nombre: /servicios/%d/nombre
  tratamiento:
    exists: /tratamientos/%d/exists

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  file:
    name: logs/reservas-service.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"
