spring:
  application:
    name: resena-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/bd_resenas?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-001-resena.sql

server:
  port: 9104  



api:
  base-url: http://api-gateway:9090
  usuario:
    exists: /usuarios/%d/exists
  servicio:
    exists: /servicios/%d/exists
  compra:
    existe: /compras/usuario/%d/servicio/%d/existe

SECRET: ${SECRET}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  file:
    name: logs/resena-service.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
    file: "%d{HH:mm:ss} %-5level %msg%n"